name = "DiffusionDefinition"
uuid = "c126fcb9-5a08-4fee-b75a-97eb446288b0"
authors = ["Marcin Mider"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
